### PR TITLE
[WIP] First draft of maintainers and sponspors sidebars

### PR DESCRIPTION
**Pull request by helmo**
relates to https://www.drupal.org/node/2164579

### CODE REVIEW

**Comment by colans** [comment]
I should probably get a logo so I stop messing up the design. ;)

**Comment by helmo** [comment]
Screenshot of the current draft, with a smaller window it start to overlap :(

selection_097

**Comment by mlutfy** [comment]
@helmo  How about moving the partner logos at the bottom? This way we don't need to worry about screen width. It might provide less visibility, but I think it's  a bit overwhelming to have logos on both sides.

aegir-project-website-t2

We could also move the logos before the 5-icon section (doc, irc, donate, etc).

aegir-project-website-t3

(I think I prefer this option)

**Comment by helmo** [comment]
I don't think we should bring the '5-icon section' down too far as they're fairly important for navigation. We might even consider moving them to the top(or duplicating them).

My thought about a separate 'maintainer companies' section was to advertise who can be hired for Aegir related work. The sponsors section is then to promote financial sponsoring.

**Comment by mlutfy** [comment]
How about this? (below)

For the list of sponsors/contributors, we can further tweak it, but I think it should be a unique listing, with some small visual cue to distinguish the level of involvement. Omega, for example, are also developers. This CiviCRM example can't be applied as-is, but I think it's a good model: https://civicrm.org/partners-contributors ("partners" are sponsors, they provide financial support).

aegir-website-20170620

**Comment by helmo** [comment]
yes +1. 
Did you do the 'sponsored' thing with CSS? 
Please commit these changes to the feature branch :)

**Comment by mlutfy** [comment]
I was playing around in The Gimp, but I will send a patch and we can do another round of review.

**Comment by omega8cc** [comment]
@colans Indeed, you need a logo! :-)

**Comment by helmo** [comment]
Now that we have a new site ... lets continue the discussion on https://gitlab.com/aegir/www.aegirproject.org/issues/18

**Pull request closed without merging**
