### PR TITLE
Bitcoin donation address

### PR DESCRIPTION
**Pull request by helmo**
@jonpugh @colans How does this look? Merge or can we make it prettier?

I'm sharing the private key with @ergonlogic to ensure access for the team.

### CODE REVIEW

**Comment by colans** [comment]
Looks good to me, but I'm not the best person to ask about making things pretty.

3 key holders would be better than 2.  Trying to find a third would be a good idea, IMHO.

**Comment by helmo** [comment]
Any volunteers? @gboudrias @mlutfy ...

**Comment by colans** [comment]
Ideally this would be someone who can deposit the funds into the bank account.

**Comment by helmo** [comment]
Lets see what comes in.

**Pull request merged**
